#!/bin/bash

set -e 

TARGET_DIR="/mit/6.148/web_scripts"

if [ -z $1 ]; then
    echo "Syncing all files"
    MODE=0
elif [ "$1" = "--text" ]; then
    echo "Syncing only text files (no images)"
    MODE=1
else
    echo "ERROR: Unrecognized flag $1"
    exit 1
fi

gulp
read -p "Athena username: " NAME

if [ $MODE = 0 ]; then
    rsync -rvP build/* $NAME@athena.dialup.mit.edu:$TARGET_DIR
else
    rsync -rvP --include '*/' --include '*.html' --include '*.css' --include '*.js' --exclude '*'  build/* $NAME@athena.dialup.mit.edu:$TARGET_DIR
fi

echo "finished!"
